### ISSUE TITLE
Is setting the organization during setup necessary?

### ISSUE THREAD

**Issue by tpetchel** [chef-partners/marketplace_image#6]
During setup, I was prompted to enter an organization. I wasn't sure if this meant the full name ("Web Development Team") or the short name ("webdev"). I entered the long name, thinking the next question would be the short version.

After setup, I logged into the management console. When I logged in, I was again prompted to enter the org name (both full and short names.) I entered a different name this time.

After that, only the org name that I entered from the management console appeared in the UI. So it appears that the org name I entered from my Chef server wasn't used.

We should either use the org name that's specified during setup (and be clear during setup which name to enter, perhaps by showing an example or saying what kind of input is allowable - spaces, numbers, symbols, etc.), or not ask the user for an org name if it's not used.

**Comment by gmiranda23** [comment]
:+1:  We should be clearer on org short name or long name and also check the inputs for invalid characters.  I don't know if we're checking password length either, but that also needs validation.

**Comment by ryancragun** [comment]
So, what happened here was that the Org name that you supplied was invalid so the org creation failed.  Now we [normalize](https://github.com/chef-partners/omnibus-marketplace/blob/ryan/add_ctl/files/chef-marketplace-ctl-commands/marketplace/helpers.rb) and [validate](https://github.com/chef-partners/omnibus-marketplace/blob/ryan/add_ctl/files/chef-marketplace-ctl-commands/marketplace/options.rb) all of the given user input.  Doing the user and org creation in the setup allows for fully unattended installs with a single `chef-server-ctl` command.

Closing as this issue is resolved in https://github.com/chef-partners/omnibus-marketplace/pull/1/files
